apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: angular-frontend
        #image: tybahmed/front:v1
        image: tybahmed/angular-fixed:v2
        ports:
        - containerPort: 8080
        env:
        - name: BASEURL
          value: "app-spring-argocd.apps.openshift.onetech-group.corp/SpringMVC/facture/retrieve-all-factures" 
        - name: PORT
          value: "31771"                          
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
