---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: argocd
type: Opaque
data:
  mysql-root-password: cm9vdA==  # base64 encoded "root"
  mysql-user-password: cm9vdA==  # base64 encoded "root"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
  namespace: argocd
  labels:
    app: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-database-name
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        # Removed MYSQL_PASSWORD to avoid conflicts
        args:
        - "--default-authentication-plugin=mysql_native_password"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 45
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - -u
            - root
            - -proot
          initialDelaySeconds: 30
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-init-script          # ← ADDED: Mount the init script
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init-script
        configMap:
          name: mysql-init-script
